version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./minecraft-data:/data
      - ./saves-to-import:/worlds:ro
    env_file:
      - ./.env
    environment:
      - EULA=${EULA}
      - MOTD=${MOTD}
      - DIFFICULTY=${DIFFICULTY}
      - ENFORCE_WHITELIST=${ENFORCE_WHITELIST}
      - WHITELIST=${WHITELIST}
      - OPS=${OPS}
      - ICON=${ICON}
      - ENABLE_RCON=${ENABLE_RCON}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - RCON_PORT=${RCON_PORT}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - ALLOW_NETHER=${ALLOW_NETHER}
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=${ANNOUNCE_PLAYER_ACHIEVEMENTS}
      - GENERATE_STRUCTURES=${GENERATE_STRUCTURES}
      - PAWN_ANIMALS=${PAWN_ANIMALS}
      - SPAWN_MONSTERS=${SPAWN_MONSTERS}
      - SPAWN_NPCS=${SPAWN_NPCS}
      - VIEW_DISTANCE=${VIEW_DISTANCE}
      - MODE=${MODE}
      - PVP=${PVP}
      - ENABLE_QUERY=${ENABLE_QUERY}
      - USE_AIKAR_FLAGS=${USE_AIKAR_FLAGS}
      - ENABLE_STATUS=${ENABLE_STATUS}
      - ONLINE_MODE=${ONLINE_MODE}
      - SERVER_NAME=${SERVER_NAME}
      - MEMORY=${MEMORY}
      - TZ=${TZ}
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    tty: true
    stdin_open: true
    deploy:
     resources:
       limits:
         memory: ${MEMORY}
