version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./minecraft-data:/data
      - ./saves-to-import:/worlds:ro
    env_file:
      - minecraft.env
    restart: always
    deploy:
     resources:
       limits:
         memory: 4G
  minecraft-map:
    image: mide/minecraft-overviewer:latest
    environment:
      - MINECRAFT_VERSION="1.17"
    volumes:environment:
      - /home/user/minecraft/:/home/minecraft/server/:ro
      - /srv/http/minecraft/:/home/minecraft/render/:rw
